### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by silfumus** [RyuuKitsune/ryuukitsune.github.io#1]
Are you still maintaining this repo?
I noticed that some of the quest and item translations are still missing (e.g: 120mm italian gun).

If you need me to contribute, just let me know.

**Comment by RyuuKitsune** [comment]
I've been pretty busy in real life recently,  I just started a new C# and SQL development internship, so that suddenly sucked away a massive portion of my free time. I totally plan on updating things (my local branch is updated to 1.6.0 upstream, though I need to bring it in line with newer updates), just it'll be a little bit until they're out.

If you'd like to contribute anything, please feel free! The XML translation files are hosted on my [ryuukitsune.github.io repository](https://github.com/RyuuKitsune/ryuukitsune.github.io), so if you want to fork those and add necessary translations, then submit me a pull request, that is totally fine by me. 

Translation files are separated into locales (en, ko-KR for English and Korean, respectively), with the files in the root directory being English (for backwards compatibility before I implemented multiple languages). Any changes to the English files must be updated in the root directory, though that's relatively simple.

Just don't worry about having to take the codebase over, though, I do fully plan on continuing! But if you want to contribute, I welcome it.

(leaving this open until I can finish the updates, as motivation)

**Comment by RyuuKitsune** [comment]
Updates complete with your pull request. Thank you again!
